#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Life', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}


#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >

  Hi! Welcome to my website! This is Wenting Zhao and you can call me Mia. Now I am a Master student studying Business Analytics at UC San Diego and will graduate in August. This program gives me the chance to jump into the true data-driven world and learn how to do analytics.
  
  Under my undergraduate degree, I studied Economics in Hangzhou and worked as a financial intern in Bank of Communications and CreditEase. After that, I knew I can't be happy if I become a banker or accountant in a financial institution, even it could be a famous one. Therefore, following by my heart, I chose to start my journey in the Internet industry, which is the domain where can push me generate fresh ideas and feel excited. Finally, I had my third internship in Beyondsoft and came here to learn data analytics. 
  
  Here, I want to share and summarize my projects with you guys and hope you can have fun! 
  
  Also, if you want to learn more about me, feel free to reach out via [my Linkedin](https://www.linkedin.com/in/wenting-zhao/) or [my Email](mailto:wentingzhao0813@163.com).
  
Life: 
  # Life

   

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#https://www.instagram.com/mia_snoopyy/'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#https://www.linkedin.com/in/wenting-zhao/'}
- {icon: 'envelope', link: '#mailto:wentingzhao0813@163.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
